SELECT * FROM customer.customers_shopping_behaviour;
SHOW COLUMNS FROM customers_shopping_behaviour;

##Q1. What is the total revenue generated by male vs. female customers?
select gender,
sum(purchase_amount) as total_revenue
FROM customers_shopping_behaviour
group by gender;

##Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id,
    gender,
    purchase_amount,
    discount_applied
FROM customers_shopping_behaviour
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount) 
      FROM customers_shopping_behaviour
  );
  
  ##Q3. Which are the top 5 products with the highest average review rating?
  SELECT 
    item_purchased,
    AVG(review_rating) AS avg_rating
FROM customers_shopping_behaviour
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

##Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customers_shopping_behaviour
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

##Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
SUM(purchase_amount) as total_purchase_amount,
AVG(purchase_amount) as average_purchase_amount,
COUNT(*) AS total_customers
FROM customers_shopping_behaviour
GROUP BY subscription_status;


##Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100 
        AS discount_percentage
FROM customers_shopping_behaviour
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

##Q7. Segment customers into New, Returning, and Loyal based on their total 
##number of previous purchases, and show the count of each segment. 
SELECT 
    CASE
        WHEN total_purchases <= 1 THEN 'New'
        WHEN total_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count;

SELECT 
    CASE 
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS segment,
    COUNT(*) AS customer_count
FROM customers_shopping_behaviour
GROUP BY segment;

##Q8. What are the top 3 most purchased products within each category? 
SELECT category,item_purchased,
       total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM customers_shopping_behaviour
    GROUP BY category, item_purchased
) AS ranked
WHERE rn <= 3
ORDER BY category, total_purchases DESC;

##Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Not Repeat Buyer'
    END AS buyer_type,
    
    COUNT(*) AS total_customers,
    
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
    
    ROUND(
        SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100, 
    2) AS subscription_rate_percent
FROM customers_shopping_behaviour
GROUP BY buyer_type;

##Q10. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers_shopping_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;

##11 What is the percentage revenue contribution of each age group?
SELECT 
	age_group,
    SUM(purchase_amount) AS total_revenue,

    ROUND(
        SUM(purchase_amount) /
        (SELECT SUM(purchase_amount) FROM customers_shopping_behaviour) * 100,
        2
    ) AS revenue_percentage

FROM customers_shopping_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;





